import { Employee } from '../../core/models/employee.model';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    department: 'Engineering',
    role: 'Senior Developer',
    status: 'active',
    joinDate: '2022-01-15',
    phone: '+1-555-0001',
    address: '123 Main St, San Francisco, CA',
    salary: 120000,
    manager: 'Jane Smith',
    bio: 'Full-stack engineer with 8+ years of experience in web development.',
  },
  {
    id: 2,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    department: 'Design',
    role: 'UX Designer',
    status: 'active',
    joinDate: '2021-03-20',
    phone: '+1-555-0002',
    address: '456 Oak Ave, New York, NY',
    salary: 95000,
    manager: 'Bob Wilson',
    bio: 'Creative designer specializing in user experience and interface design.',
  },
  {
    id: 3,
    name: 'Bob Martinez',
    email: 'bob.martinez@example.com',
    department: 'Marketing',
    role: 'Marketing Manager',
    status: 'on-leave',
    joinDate: '2020-06-10',
    phone: '+1-555-0003',
    address: '789 Pine Rd, Austin, TX',
    salary: 105000,
    manager: 'Sarah Davis',
    bio: 'Marketing professional with expertise in digital campaigns.',
  },
  {
    id: 4,
    name: 'Carol White',
    email: 'carol.white@example.com',
    department: 'Engineering',
    role: 'DevOps Engineer',
    status: 'inactive',
    joinDate: '2019-11-05',
    phone: '+1-555-0004',
    address: '321 Elm St, Seattle, WA',
    salary: 115000,
    manager: 'Jane Smith',
    bio: 'Infrastructure specialist focused on CI/CD and cloud platforms.',
  },
  {
    id: 5,
    name: 'David Brown',
    email: 'david.brown@example.com',
    department: 'Sales',
    role: 'Sales Representative',
    status: 'active',
    joinDate: '2023-02-14',
    phone: '+1-555-0005',
    address: '654 Maple Dr, Boston, MA',
    salary: 85000,
    manager: 'Michael Taylor',
    bio: 'Results-driven sales professional with a track record of exceeding targets.',
  },
];
